### ISSUE TITLE
Question: nginx config file location

### ISSUE THREAD

**Issue by bruno-** [kalys/capistrano-nginx-unicorn#21]
Hi,
I have a question related to nginx config file location.
Why is the actual configuration file copied to `/etc/nginx/sites-available/`? In source code it's [this line](https://github.com/kalys/capistrano-nginx-unicorn/blob/master/lib/capistrano/tasks/nginx.rake#L12).

The alternative to that path would be having the config file in `shared_path/config/nginx`. From there, it would be symlinked directly to `sites-enabled` directory. (this is how I learned to do it from Ryan Bates' railscasts).

So what are the pros of keeping the config file in `sites-available` dir?
Thanks

**Comment by rockaBe** [comment]
@bruno- ,

I think it is due to the standard way nginx server configs are structured.
The config root for nginx is located at `/etc/nginx` where there are two directories `sites-available` and `sites-enabled`(where all your different config files go to `sites-available` and you create symlinks to these in the `sites-enabled` directory).

Following this convention, it is alway clear, where your running server configurations are held.
Hope that helps :dart:

**Comment by bruno-** [comment]
@rockaBe thanks!
